name: dotnet test
on:
    pull_request:
        branches:
            - main
        paths:
            - 'backend/**'
    push:
        branches:
            - main
        paths:
            - 'backend/**'
jobs:
    dotnet_test:
        name: dotnet test
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x
                  # https://github.com/actions/setup-dotnet/issues/563
                  # global-json-file: backend/global.json
            - name: Build and test
              run: |
                cd backend
                dotnet restore
                dotnet build
                dotnet test --configuration Debug --logger trx --collect:"XPlat Code Coverage"
            - name: Test Report
              uses: dorny/test-reporter@v1.9.1
              if: success() || failure()
              with:
                name: Unit Test Report
                path: '**/*.trx'
                reporter: dotnet-trx

